"""Changed table Items -added check constraint for price

Revision ID: 1e24173502a7
Revises: ec01989cffb8
Create Date: 2023-10-27 13:40:17.018924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e24173502a7'
down_revision: Union[str, None] = 'ec01989cffb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
