"""Changed field, that specify on id model. Created_at has been moved from Purchases to purchases_item_user

Revision ID: 3d054e81730f
Revises: e1d75584c5a7
Create Date: 2023-09-28 14:21:30.078298

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d054e81730f'
down_revision: Union[str, None] = 'e1d75584c5a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_item_user', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('card_item_user_card_id_fkey', 'card_item_user', type_='foreignkey')
    op.create_foreign_key(None, 'card_item_user', 'cards', ['id'], ['id'])
    op.drop_column('card_item_user', 'card_id')
    op.add_column('favorites_item_user', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('favorites_item_user_favorite_id_fkey', 'favorites_item_user', type_='foreignkey')
    op.create_foreign_key(None, 'favorites_item_user', 'favorites', ['id'], ['id'])
    op.drop_column('favorites_item_user', 'favorite_id')
    op.add_column('purchase_item_user', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('purchase_item_user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint('purchase_item_user_purchase_id_fkey', 'purchase_item_user', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_item_user', 'purchases', ['id'], ['id'])
    op.drop_column('purchase_item_user', 'purchase_id')
    op.drop_column('purchases', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('purchase_item_user', sa.Column('purchase_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'purchase_item_user', type_='foreignkey')
    op.create_foreign_key('purchase_item_user_purchase_id_fkey', 'purchase_item_user', 'purchases', ['purchase_id'], ['id'])
    op.drop_column('purchase_item_user', 'created_at')
    op.drop_column('purchase_item_user', 'id')
    op.add_column('favorites_item_user', sa.Column('favorite_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'favorites_item_user', type_='foreignkey')
    op.create_foreign_key('favorites_item_user_favorite_id_fkey', 'favorites_item_user', 'favorites', ['favorite_id'], ['id'])
    op.drop_column('favorites_item_user', 'id')
    op.add_column('card_item_user', sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'card_item_user', type_='foreignkey')
    op.create_foreign_key('card_item_user_card_id_fkey', 'card_item_user', 'cards', ['card_id'], ['id'])
    op.drop_column('card_item_user', 'id')
    # ### end Alembic commands ###
