"""Changed table purchase_item_user (added column price)

Revision ID: 6f142f6d8dc9
Revises: 7b1c08a38ed7
Create Date: 2023-10-08 13:17:26.417133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f142f6d8dc9'
down_revision: Union[str, None] = '7b1c08a38ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_item_user', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_item_user', 'price')
    # ### end Alembic commands ###
