"""Changed field Profile photo (added default)

Revision ID: 70fa5ae28e15
Revises: b9bef094929e
Create Date: 2023-09-15 17:10:19.621184

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '70fa5ae28e15'
down_revision: Union[str, None] = 'b9bef094929e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
