"""Added item_id to Rating

Revision ID: 7271432529ae
Revises: da9a5ea59374
Create Date: 2023-09-17 16:25:55.266201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7271432529ae'
down_revision: Union[str, None] = 'da9a5ea59374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('item_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ratings', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_column('ratings', 'item_id')
    # ### end Alembic commands ###
