"""Changed table purchase_item_user

Revision ID: 7b1c08a38ed7
Revises: a21cfd30b2cc
Create Date: 2023-10-08 13:14:05.252317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b1c08a38ed7'
down_revision: Union[str, None] = 'a21cfd30b2cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_item_user', sa.Column('email', sa.String(), nullable=True))
    op.add_column('purchase_item_user', sa.Column('name', sa.String(), nullable=True))
    op.add_column('purchase_item_user', sa.Column('second_name', sa.String(), nullable=True))
    op.add_column('purchase_item_user', sa.Column('phone_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_item_user', 'phone_number')
    op.drop_column('purchase_item_user', 'second_name')
    op.drop_column('purchase_item_user', 'name')
    op.drop_column('purchase_item_user', 'email')
    # ### end Alembic commands ###
