"""Changed table Profiles, default=1

Revision ID: 99da6e22ef92
Revises: e209041fe7ef
Create Date: 2023-10-27 14:21:26.116729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99da6e22ef92'
down_revision: Union[str, None] = 'e209041fe7ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
