"""refactor tables

Revision ID: a21cfd30b2cc
Revises: 2d1ea6ca08b8
Create Date: 2023-10-07 12:29:41.156102

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a21cfd30b2cc'
down_revision: Union[str, None] = '2d1ea6ca08b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_item_user',
    sa.Column('related_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['related_id'], ['carts.id'], )
    )
    op.drop_table('card_item_user')
    op.drop_table('cards')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_item_user',
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('related_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='card_item_user_item_id_fkey'),
    sa.ForeignKeyConstraint(['related_id'], ['cards.id'], name='card_item_user_related_id_fkey')
    )
    op.create_table('cards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name='cards_profile_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cards_pkey')
    )
    op.drop_table('cart_item_user')
    op.drop_table('carts')
    # ### end Alembic commands ###
