"""changed firld that specify on id related model

Revision ID: bf867e269adf
Revises: 88dcffe7c412
Create Date: 2023-09-28 14:37:03.992179

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bf867e269adf'
down_revision: Union[str, None] = '88dcffe7c412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_item_user', sa.Column('related_id', sa.Integer(), nullable=False))
    op.drop_constraint('card_item_user_card_id_fkey', 'card_item_user', type_='foreignkey')
    op.create_foreign_key(None, 'card_item_user', 'cards', ['related_id'], ['id'])
    op.drop_column('card_item_user', 'card_id')
    op.add_column('favorites_item_user', sa.Column('related_id', sa.Integer(), nullable=False))
    op.drop_constraint('favorites_item_user_favorite_id_fkey', 'favorites_item_user', type_='foreignkey')
    op.create_foreign_key(None, 'favorites_item_user', 'favorites', ['related_id'], ['id'])
    op.drop_column('favorites_item_user', 'favorite_id')
    op.add_column('purchase_item_user', sa.Column('related_id', sa.Integer(), nullable=False))
    op.drop_constraint('purchase_item_user_purchase_id_fkey', 'purchase_item_user', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_item_user', 'purchases', ['related_id'], ['id'])
    op.drop_column('purchase_item_user', 'purchase_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_item_user', sa.Column('purchase_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'purchase_item_user', type_='foreignkey')
    op.create_foreign_key('purchase_item_user_purchase_id_fkey', 'purchase_item_user', 'purchases', ['purchase_id'], ['id'])
    op.drop_column('purchase_item_user', 'related_id')
    op.add_column('favorites_item_user', sa.Column('favorite_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'favorites_item_user', type_='foreignkey')
    op.create_foreign_key('favorites_item_user_favorite_id_fkey', 'favorites_item_user', 'favorites', ['favorite_id'], ['id'])
    op.drop_column('favorites_item_user', 'related_id')
    op.add_column('card_item_user', sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'card_item_user', type_='foreignkey')
    op.create_foreign_key('card_item_user_card_id_fkey', 'card_item_user', 'cards', ['card_id'], ['id'])
    op.drop_column('card_item_user', 'related_id')
    # ### end Alembic commands ###
