"""Create database

Revision ID: dd37cb060a5c
Revises: 
Create Date: 2023-11-12 15:36:30.743453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'dd37cb060a5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('parent', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['parent'], ['categories.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('images',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('file_path', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('file_path')
                    )
    op.create_table('items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('price', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.CheckConstraint('price >= 1', name='check_price'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('hash_password', sa.String(), nullable=False),
                    sa.Column('is_admin', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('category_item',
                    sa.Column('category_id', sa.Integer(), nullable=False),
                    sa.Column('item_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
                    sa.ForeignKeyConstraint(['item_id'], ['items.id'], )
                    )
    op.create_table('item_image',
                    sa.Column('item_id', sa.Integer(), nullable=False),
                    sa.Column('image_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
                    sa.ForeignKeyConstraint(['item_id'], ['items.id'], )
                    )
    op.create_table('profiles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('second_name', sa.String(), nullable=True),
                    sa.Column('number_phone', sa.BigInteger(), nullable=True),
                    sa.Column('photo', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['photo'], ['images.id'], ),
                    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user')
                    )
    op.create_table('reviews',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.String(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('item_id', sa.Integer(), nullable=False),
                    sa.Column('rate', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.CheckConstraint('rate <= 5 and rate >= 1', name='check_rate'),
                    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('carts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('profile_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('favorites',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('profile_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('purchases',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('profile_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('cart_item_user',
                    sa.Column('related_id', sa.Integer(), nullable=False),
                    sa.Column('item_id', sa.Integer(), nullable=False),
                    sa.Column('count', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
                    sa.ForeignKeyConstraint(['related_id'], ['carts.id'], )
                    )
    op.create_table('favorites_item_user',
                    sa.Column('related_id', sa.Integer(), nullable=False),
                    sa.Column('item_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
                    sa.ForeignKeyConstraint(['related_id'], ['favorites.id'], )
                    )
    op.create_table('purchase_item_user',
                    sa.Column('related_id', sa.Integer(), nullable=False),
                    sa.Column('item_id', sa.Integer(), nullable=True),
                    sa.Column('count', sa.Integer(), nullable=False),
                    sa.Column('price', sa.Integer(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('second_name', sa.String(), nullable=True),
                    sa.Column('phone_number', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['related_id'], ['purchases.id'], )
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_item_user')
    op.drop_table('favorites_item_user')
    op.drop_table('cart_item_user')
    op.drop_table('purchases')
    op.drop_table('favorites')
    op.drop_table('carts')
    op.drop_table('reviews')
    op.drop_table('profiles')
    op.drop_table('item_image')
    op.drop_table('category_item')
    op.drop_table('users')
    op.drop_table('items')
    op.drop_table('images')
    op.drop_table('categories')
    # ### end Alembic commands ###
