"""Changed table purchse_item_user ondelete

Revision ID: e209041fe7ef
Revises: d489ededc859
Create Date: 2023-10-27 14:01:09.480520

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e209041fe7ef'
down_revision: Union[str, None] = 'd489ededc859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('purchase_item_user_item_id_fkey', 'purchase_item_user', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_item_user', 'items', ['item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_item_user', type_='foreignkey')
    op.create_foreign_key('purchase_item_user_item_id_fkey', 'purchase_item_user', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###
