"""Added cascade for parent of table category

Revision ID: e55a9e68669a
Revises: 7eddf3984e19
Create Date: 2023-10-16 12:34:02.750029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55a9e68669a'
down_revision: Union[str, None] = '7eddf3984e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_parent_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'categories', ['parent'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key('categories_parent_fkey', 'categories', 'categories', ['parent'], ['id'])
    # ### end Alembic commands ###
